on:
  push:
    branches:
    - main
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          repository: repurpos
          tags: latest
          #context: .
          outputs: type=docker,dest=/tmp/repurpos.tar
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: $(docker load -i /tmp/repurpos.tar)repurpos
          path: /dist_electron/.
      - name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: dist
